### ISSUE TITLE
Update to completions path breaks loading

### ISSUE THREAD

**Issue by jackmac92** [kiurchv/asdf.plugin.zsh#2]
I still see this sitting in the old location: https://github.com/asdf-vm/asdf/tree/master/completions and thus I have an error while loading this plugin.

_Originally posted by @bartoszmajsak in https://github.com/kiurchv/asdf.plugin.zsh/commit/bcfe332c129347f9b911a7a83e83d86ad087eba5#commitcomment-31870528_

**Comment by jackmac92** [comment]
I'm facing the same issue as the one I quoted above

**Comment by FlorinPopaCodes** [comment]
I'm having the same issue described above. On @stigkj fork the https://github.com/kiurchv/asdf.plugin.zsh/commit/bcfe332c129347f9b911a7a83e83d86ad087eba5 commit has been reverted by https://github.com/stigkj/asdf.plugin.zsh/commit/a98f3c62672b0e48a23922e8001eebf7c6e58cd5.

@kiurchv would it be possible to do the same here?

**Comment by kiurchv** [comment]
Done in #3. Sorry for long answer
